version: '3.7'

services:
  db:
    restart: unless-stopped
    image: postgres:latest
    hostname: postgres
    container_name: bookings_db
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  web:
    restart: unless-stopped
    container_name: bookings_web
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python3.7 main.py"
    ports:
      - 9000:9000
    depends_on:
      - db
    links:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

